version: 0.2
phases:
  install:
    commands:
      - . /root/.bashrc
      - npm install
  pre_build:
    commands:
      - npm run lint
      - npm run flow:check
      - npm test
  build:
    commands:
      - npm run build
