export default {

  // Auth action types
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGOUT: 'LOGOUT',
  SESSION_RESTORED: 'SESSION_RESTORED',
  MFA_SUCCESS: 'MFA_SUCCESS',
  FETCH_USERLIST_SUCCESS: 'FETCH_USERLIST_SUCCESS',
  FETCH_USERLIST_ERROR: 'FETCH_USERLIST_ERROR'
  

};
